[information]
name = "bamzi"
background = "dark"
author = 'Bamzi'

[palette]
fg = '#e8f5e0'
bg = '#18251d'

alt_fg = '#c2d0cb'
alt_bg = '#293d30'

line = '#253c32'
dark_gray = '#46534a'
gray = '#67796d'
md_gray = '#8b9c91'
light_gray = '#b5c0b8'
context = '#47b364'
menu_bg = '#254b32'

red = '#c78f8f'
blue = '#96a3b6'
vivid_blue = '#96bfe3'
light_blue = '#c0cad8'
green = '#83d07c'
light_green = '#abdca7'
cyan = '#a9dbd0'
orange = '#d9ab9b'
yellow = '#d6d39e'
yellow_orange = '#d9c69b'
purple = '#c0b6c9'
magenta = '#cfabb8'

cursor_fg = '#515252'
cursor_bg = '#a5b6af'

sign_add = '#0e8b57'
sign_change = '#425094'
sign_delete = '#7f343d'

sign_add_alt = '#73C991'
sign_change_alt = '#CCA700'

error = '#de4a4a'
warn = '#d59144'
info = '#b6df5d'
hint = '#62bdc0'

error_bg = '#1c2b26'
warn_bg = '#1c2b26'
info_bg = '#1c2b26'
hint_bg = '#1c2b26'

reference = '#363636'
success_green = '#65c360'
folder_blue = '#879ec4'


ui1 = '#499763'
ui2 = '#0c1810'
ui3 = '#53ac71'
ui4 = '#a9d6b8'
ui5 = '#1c3b26'
ui6 = '#91e679'
ui7 = '#a59ab1'
ui8 = '#a8c270'
ui9 = '#d8d7cf'
ui10 = '#88f5f7'

[Editor]
Normal = 'fg bg'
SignColumn = '- bg'
MsgArea = 'fg bg'
ModeMsg = 'fg alt_bg'
MsgSeparator = 'fg bg'
SpellBad = '- - c red'
SpellCap = '- - c yellow'
SpellLocal = '- - u green'
SpellRare = '- - u purple'
NormalNC = 'fg bg'
Pmenu = 'light_gray menu_bg'
PmenuSel = '- ui2'
WildMenu = 'fg ui2'
CursorLineNr = 'light_gray'
Folded = 'gray alt_bg'
FoldColumn = 'gray alt_bg'
LineNr = 'dark_gray -'
FloatBoder = 'dark_gray alt_bg'
Whitespace = 'bg'
VertSplit = 'dark_gray bg'
CursorLine = '- alt_bg'
CursorColumn = '- alt_bg'
ColorColumn = '- alt_bg'
NormalFloat = '- alt_bg'
Visual = '- ui1'
VisualNOS = '- alt_bg'
WarningMsg = 'error bg'
DiffText = 'alt_bg sign_delete'
DiffAdd = 'alt_bg sign_add'
DiffChange = 'alt_bg sign_change u'
DiffDelete = 'alt_bg sign_delete'
QuickFixLine = '- ui2'
PmenuSbar = '- alt_bg'
PmenuThumb = '- gray'
MatchWord = '- reference'
MatchParen = 'hint reference'
MatchWordCur = '- reference'
MatchParenCur = '- reference'
Cursor = 'cursor_fg cursor_bg'
lCursor = 'cursor_fg cursor_bg'
CursorIM = 'cursor_fg cursor_bg'
TermCursor = 'cursor_fg cursor_bg'
TermCursorNC = 'cursor_fg cursor_bg'
Conceal = 'gray'
Directory = 'folder_blue'
SpecialKey = 'green - b'
ErrorMsg = 'error bg b'
Search = '- ui5'
IncSearch = '- ui7'
Substitute = '- ui7'
MoreMsg = 'orange'
Question = 'orange'
EndOfBuffer = 'bg'
NonText = 'bg'
TabLine = 'light_gray line'
TabLineSel = 'fg line'
TabLineFill = 'line line'

[Code]
Comment = 'dark_gray'
Variable = 'ui4'
String = 'ui8'
Character = 'orange'
Number = 'ui10'
Float = 'ui10'
Boolean = 'cyan'
Constant = 'red'
Type = 'yellow_orange'
Function = 'context'
Method = 'yellow'
Keyword = 'light_gray'
Conditional = 'red'
Repeat = 'purple'
Operator = 'ui9'
PreProc = 'ui3'
Include = 'purple'
Exception = 'magenta'
StorageClass = 'cyan'
Structure = 'green'
Typedef = 'yellow_orange'
Define = 'purple'
Macro = 'ui7'
Debug = 'sign_delete'
Title = 'ui4 - b'
Label = 'ui8'
SpecialChar = 'purple'
Delimiter = 'blue'
SpecialComment = 'ui5'
Tag = 'ui9'
Bold = '- - b'
Italic = '- - i'
Underlined = '- - u'
Ignore = 'warn - b'
Todo = 'sign_change_alt - b'
Error = 'error - b'
Statement = 'purple'
Identifier = 'light_blue'
PreCondit = 'purple'
Special = 'orange'

[Treesitter]
TSComment = 'dark_gray - i'
TSVariable = 'link:Variable'
TSString = 'link:String'
TSStringRegex = 'link:String'
TSStringEscape = 'link:String'
TSCharacter = 'link:String'
TSCharacterSpecial = 'link:SpecialChar'
TSNumber = 'link:Number'
TSFloat = 'link:Float'
TSBoolean = 'link:Boolean'
TSConstant = 'link:Constant'
TSConstBuiltin = 'link:Constant'
TSConstructor = 'link:Type'
TSType = 'link:Type'
TSInclude = 'link:Include'
TSException = 'link:Exception'
TSKeyword = 'link:Keyword'
TSKeywordReturn = 'magenta'
TSKeywordOperator = 'link:Include'
TSKeywordFunction = 'context'
TSFunction = 'link:Function'
TSFuncBuiltin = 'link:Type'
TSMethod = 'yellow'
TSFuncMacro = 'link:Function'
TSConditional = 'link:Conditional'
TSRepeat = 'link:Repeat'
TSOperator = 'link:Operator'
TSPreProc = 'link:PreProc'
TSStorageClass = 'link:StorageClass'
TSStructure = 'link:Structure'
TSTypeDefinition = 'link:Typedef'
TSDefine = 'link:Define'
TSNote = 'link:Comment'
TSTodo = 'link:Todo'
TSDebug = 'link:Debug'
TSDanger = 'link:Error'
TSTitle = 'link:Title'
TSLabel = 'link:Label'
TSPunctDelimiter = 'link:Delimiter'
TSTagDelimiter = 'gray'
TSPunctBracket = 'link:Delimiter'
TSPunctSpecial = 'link:Delimiter'
TSTag = 'link:Tag'
TSStrong = 'link:Bold'
TSEmphasis = 'link:Italic'
TSUnderline = 'link:Underline'
TSStrike = '- - s'
TSStringSpecial = 'fg'
TSEnvironmentName = 'cyan'
TSVariableBuiltin = 'cyan'
TSConstMacro = 'green'
TSTypeBuiltin = 'fg'
TSAnnotation = 'blue'
TSNamespace = 'cyan'
TSSymbol = 'fg'
TSField = 'green'
TSProperty = 'fg'
TSParameter = 'light_blue'
TSParameterReference = 'light_blue'
TSAttribute = 'cyan'
TSText = 'fg'
TSTagAttribute = 'light_blue - i'
TSError = 'error'
TSWarning = 'warn'
TSQueryLinterError = 'error'
TSURI = 'cyan - u'
TSMath = 'yellow'
TSLiteral = 'orange'

[markdown]
markdownBlockquote = 'orange'
markdownCode = 'orange'
markdownCodeBlock = 'orange'
markdownCodeDelimiter = 'orange'
markdownH1 = 'link:Title'
markdownH2 = 'link:Title'
markdownH3 = 'link:Title'
markdownH4 = 'link:Title'
markdownH5 = 'link:Title'
markdownH6 = 'link:Title'
markdownHeadingDelimiter = 'blue'
markdownHeadingRule = 'fg - b'
markdownId = 'link:Identifier'
markdownIdDeclaration = 'blue'
markdownIdDelimiter = 'light_gray'
markdownLinkDelimiter = 'light_gray'
markdownBold = 'green - b'
markdownItalic = 'link:Italic'
markdownBoldItalic = 'yellow - bi'
markdownListMarker = 'green'
markdownOrderedListMarker = 'purple'
markdownRule = 'gray'
markdownUrl = 'cyan - t'
markdownLinkText = 'blue'
markdownFootnote = 'orange'
markdownFootnoteDefinition = 'orange'
markdownEscape = 'yellow'

[Whichkey]
WhichKey = 'purple'
WhichKeySeperator = 'green'
WhichKeyGroup = 'yellow_orange'
WhichKeyDesc = 'fg'
WhichKeyFloat = '- alt_bg'

[Git]
SignAdd = 'sign_add'
SignChange = 'sign_change'
SignDelete = 'sign_delete'
GitSignsAdd = 'sign_add'
GitSignsChange = 'sign_change'
GitSignsDelete = 'sign_delete'

[LSP]
DiagnosticHint = 'hint'
DiagnosticInfo = 'info'
DiagnosticWarn = 'warn'
DiagnosticError = 'error'
DiagnosticOther = 'ui8'
DiagnosticSignHint = 'link:DiagnosticHint'
DiagnosticSignInfo = 'link:DiagnosticInfo'
DiagnosticSignWarn = 'link:DiagnosticWarn'
DiagnosticSignError = 'link:DiagnosticError'
DiagnosticSignOther = 'link:DiagnosticOther'
DiagnosticSignWarning = 'link:DiagnosticWarn'
DiagnosticFloatingHint = 'link:DiagnosticHint'
DiagnosticFloatingInfo = 'link:DiagnosticInfo'
DiagnosticFloatingWarn = 'link:DiagnosticWarn'
DiagnosticFloatingError = 'link:DiagnosticError'
DiagnosticUnderlineHint = '- - c hint'
DiagnosticUnderlineInfo = '- - c info'
DiagnosticUnderlineWarn = '- - c warn'
DiagnosticUnderlineError = '- - c error'
DiagnosticSignInformation = 'link:DiagnosticInfo'
DiagnosticVirtualTextHint = 'hint hint_bg'
DiagnosticVirtualTextInfo = 'info info_bg'
DiagnosticVirtualTextWarn = 'warn warn_bg'
DiagnosticVirtualTextError = 'error error_bg'

LspDiagnosticsError = 'error'
LspDiagnosticsWarning = 'warn'
LspDiagnosticsInfo = 'info'
LspDiagnosticsInformation = 'link:LspDiagnosticsInfo'
LspDiagnosticsHint = 'hint'
LspDiagnosticsDefaultError = 'link:LspDiagnosticsError'
LspDiagnosticsDefaultWarning = 'link:LspDiagnosticsWarning'
LspDiagnosticsDefaultInformation = 'link:LspDiagnosticsInfo'
LspDiagnosticsDefaultInfo = 'link:LspDiagnosticsInfo'
LspDiagnosticsDefaultHint = 'link:LspDiagnosticsHint'
LspDiagnosticsVirtualTextError = 'link:DiagnosticVirtualTextError'
LspDiagnosticsVirtualTextWarning = 'link:DiagnosticVirtualTextWarn'
LspDiagnosticsVirtualTextInformation = 'link:DiagnosticVirtualTextInfo'
LspDiagnosticsVirtualTextInfo = 'link:DiagnosticVirtualTextInfo'
LspDiagnosticsVirtualTextHint = 'link:DiagnosticVirtualTextHint'
LspDiagnosticsFloatingError = 'link:LspDiagnosticsError'
LspDiagnosticsFloatingWarning = 'link:LspDiagnosticsWarning'
LspDiagnosticsFloatingInformation = 'link:LspDiagnosticsInfo'
LspDiagnosticsFloatingInfo = 'link:LspDiagnosticsInfo'
LspDiagnosticsFloatingHint = 'link:LspDiagnosticsHint'
LspDiagnosticsSignError = 'link:LspDiagnosticsError'
LspDiagnosticsSignWarning = 'link:LspDiagnosticsWarning'
LspDiagnosticsSignInformation = 'link:LspDiagnosticsInfo'
LspDiagnosticsSignInfo = 'link:LspDiagnosticsInfo'
LspDiagnosticsSignHint = 'link:LspDiagnosticsHint'

NvimTreeLspDiagnosticsError = 'link:LspDiagnosticsError'
NvimTreeLspDiagnosticsWarning = 'link:LspDiagnosticsWarning'
NvimTreeLspDiagnosticsInformation = 'link:LspDiagnosticsInfo'
NvimTreeLspDiagnosticsInfo = 'link:LspDiagnosticsInfo'
NvimTreeLspDiagnosticsHint = 'link:LspDiagnosticsHint'

LspDiagnosticsUnderlineError = 'link:DiagnosticUnderlineError'
LspDiagnosticsUnderlineWarning = 'link:DiagnosticUnderlineWarn'
LspDiagnosticsUnderlineInformation = 'link:DiagnosticUnderlineInfo'
LspDiagnosticsUnderlineInfo = 'link:DiagnosticUnderlineInfo'
LspDiagnosticsUnderlineHint = 'link:DiagnosticUnderlineHint'

LspReferenceRead = '- reference'
LspReferenceText = '- reference'
LspReferenceWrite = '- reference'

LspCodeLens = 'context - i'
LspCodeLensSeparator = 'context - i'

[Quickscope]
QuickScopePrimary = '#ba3bb4 - u'
QuickScopeSecondary = '#52b7c7 - u'

[Telescope]
TelescopeSelection = '- ui2'
TelescopeSelectionCaret = 'red ui2'
TelescopeMatching = 'info - bi'
TelescopeBorder = 'alt_fg'
TelescopeNormal = 'fg menu_bg'
TelescopePromptPrefix = "hint"
TelescopePromptTitle = "ui6 - b"
TelescopeResultsTitle = "ui6 - b"
TelescopePreviewTitle = "ui6 - b"
TelescopePromptCounter = "red"
TelescopePreviewHyphen = "red"

[NvimTree]
NvimTreeFolderIcon = 'link:Directory'
NvimTreeIndentMarker = 'context'
NvimTreeNormal = 'fg alt_bg'
NvimTreeVertSplit = 'alt_bg alt_bg'
NvimTreeFolderName = 'link:Directory'
NvimTreeOpenedFolderName = 'folder_blue - bi'
NvimTreeEmptyFolderName = 'gray - i'
NvimTreeGitIgnored = 'gray - i'
NvimTreeImageFile = 'light_gray'
NvimTreeSpecialFile = 'orange'
NvimTreeEndOfBuffer = 'alt_bg'
NvimTreeCursorLine = '- line'
NvimTreeGitStaged = 'sign_add_alt'
NvimTreeGitNew = 'sign_add_alt'
NvimTreeGitRenamed = 'sign_add_alt'
NvimTreeGitDeleted = 'sign_delete'
NvimTreeGitMerge = 'sign_change_alt'
NvimTreeGitDirty = 'sign_change_alt'
NvimTreeSymlink = 'cyan'
NvimTreeRootFolder = 'fg - b'
NvimTreeExecFile = 'info'

[Lir]
LirFloatNormal = 'fg alt_bg'
LirDir = 'link:Directory'
LirSymLink = 'cyan'
LirEmptyDirText = 'gray - i'

[Buffer]
BufferCurrent = 'fg bg'
BufferCurrentIndex = 'fg bg'
BufferCurrentMod = 'info bg'
BufferCurrentSign = 'hint bg'
BufferCurrentTarget = 'red bg b'

BufferVisible = 'fg bg'
BufferVisibleIndex = 'fg bg'
BufferVisibleMod = 'info bg'
BufferVisibleSign = 'gray bg'
BufferVisibleTarget = 'red bg b'

BufferInactive = 'gray alt_bg'
BufferInactiveIndex = 'gray alt_bg'
BufferInactiveMod = 'info alt_bg'
BufferInactiveSign = 'gray alt_bg'
BufferInactiveTarget = 'red alt_bg b'

[StatusLine]
StatusLine = 'context bg'
StatusLineNC = 'line bg'
StatusLineSeparator = 'line'
StatusLineTerm = 'line'
StatusLineTermNC = 'line'

[IndentBlankline]
IndentBlanklineContextChar = 'context'
IndentBlanklineContextStart = '- - u'
IndentBlanklineChar = 'dark_gray'
# IndentBlanklineSpaceCharBlankline = 'info'
# IndentBlanklineSpaceChar = 'cyan_test'

[Dashboard]
DashboardHeader = 'blue'
DashboardCenter = 'purple'
DashboardFooter = 'cyan'

[DiffView]
DiffViewNormal = 'gray alt_bg'
DiffviewStatusAdded = 'sign_add'
DiffviewStatusModified = 'sign_change'
DiffviewStatusRenamed = 'sign_change'
DiffviewStatusDeleted = 'sign_delete'
DiffviewFilePanelInsertion = 'sign_add'
DiffviewFilePanelDeletion = 'sign_delete'
DiffviewVertSplit = '- bg'

[Bookmarks]
BookmarkSign = 'sign_change'
BookmarkAnnotationSign = 'yellow'
BookmarkLine = 'ui2'
BookmarkAnnotationLine = 'ui2'

[Bqf]
BqfPreviewBorder = 'fg'
BqfPreviewRange = '- ui2'
# BqfPreviewFloat = 'fg'
# BqfPreviewCursor = ''
# BqfSign = ''

[Cmp]
CmpItemAbbrDeprecated = 'gray - s'
CmpItemAbbrMatch = 'ui3'
CmpItemAbbrMatchFuzzy = 'ui3'

CmpItemKindFunction = 'ui8'
CmpItemKindMethod = 'ui8'
CmpItemKindConstructor = 'ui6'
CmpItemKindClass = 'ui6'
CmpItemKindEnum = 'ui6'
CmpItemKindEvent = 'info'
CmpItemKindInterface = 'ui6'
CmpItemKindStruct = 'ui6'
CmpItemKindVariable = 'ui7'
CmpItemKindField = 'ui7'
CmpItemKindProperty = 'ui7'
CmpItemKindEnumMember = 'green'
CmpItemKindConstant = 'ui4'
CmpItemKindKeyword = 'fg'
CmpItemKindModule = 'cyan'
CmpItemKindValue = 'fg'
CmpItemKindUnit = 'fg'
CmpItemKindText = 'fg'
CmpItemKindSnippet = 'fg'
CmpItemKindFile = 'fg'
CmpItemKindFolder = 'fg'
CmpItemKindColor = 'fg'
CmpItemKindReference = 'cyan'
CmpItemKindOperator = 'fg'
CmpItemKindTypeParameter = 'cyan'

[Navic]
NavicIconsFile = 'link:CmpItemKindFile'
NavicIconsModule = 'link:CmpItemKindModule'
NavicIconsNamespace = 'link:CmpItemKindModule'
NavicIconsPackage = 'link:CmpItemKindModule'
NavicIconsClass = 'link:CmpItemKindClass'
NavicIconsMethod = 'link:CmpItemKindMethod'
NavicIconsProperty = 'link:CmpItemKindProperty'
NavicIconsField = 'link:CmpItemKindField'
NavicIconsConstructor = 'link:CmpItemKindConstructor'
NavicIconsEnum = 'link:CmpItemKindEnum'
NavicIconsInterface = 'link:CmpItemKindInterface'
NavicIconsFunction = 'link:CmpItemKindFunction'
NavicIconsVariable = 'link:CmpItemKindVariable'
NavicIconsConstant = 'link:CmpItemKindConstant'
NavicIconsString = 'link:String'
NavicIconsNumber = 'link:Number'
NavicIconsBoolean = 'link:Boolean'
NavicIconsArray = 'link:CmpItemKindClass'
NavicIconsObject = 'link:CmpItemKindClass'
NavicIconsKey = 'link:CmpItemKindKeyword'
NavicIconsKeyword = 'link:CmpItemKindKeyword'
NavicIconsNull = 'blue'
NavicIconsEnumMember = 'link:CmpItemKindEnumMember'
NavicIconsStruct = 'link:CmpItemKindStruct'
NavicIconsEvent = 'link:CmpItemKindEvent'
NavicIconsOperator = 'link:CmpItemKindOperator'
NavicIconsTypeParameter = 'link:CmpItemKindTypeParameter'
NavicText = 'gray'
NavicSeparator = 'context'

[Packer]
packerString = 'ui6'
packerHash = 'ui4'
packerOutput = 'ui8'
packerRelDate = 'gray'
packerSuccess = 'success_green'
packerStatusSuccess = 'ui4'

[SymbolOutline]
SymbolsOutlineConnector = 'gray'
FocusedSymbol = '- #36383F'

[Notify]
NotifyERRORBorder = '#9d4848'
NotifyWARNBorder = '#9d7448'
NotifyINFOBorder = 'ui1'
NotifyDEBUGBorder = 'gray'
NotifyTRACEBorder = '#4d3b4f'
NotifyERRORIcon = 'error'
NotifyWARNIcon = 'warn'
NotifyINFOIcon = 'ui4'
NotifyDEBUGIcon = 'gray'
NotifyTRACEIcon = 'ui8'
NotifyERRORTitle = 'error'
NotifyWARNTitle = 'warn'
NotifyINFOTitle = 'ui4'
NotifyDEBUGTitle = 'gray'
NotifyTRACETitle = 'ui8'
# NotifyERRORBody = Normal
# NotifyWARNBody = Normal
# NotifyINFOBody = Normal
# NotifyDEBUGBody = Normal
# NotifyTRACEBody = Normal

[TreesitterContext]
TreesitterContext = '- alt_bg'

[Hop]
HopNextKey = '#6ae2e0'
HopNextKey1 = '#e799f5'
HopNextKey2 = '#cef89b'
HopUnmatched = 'gray'
HopPreview = '#a3a8a6'
# HopCursor = ''

[Crates]
CratesNvimLoading = 'hint'
CratesNvimVersion = 'hint'
# CratesNvimPreRelease =
# CratesNvimYanked =
# CratesNvimNoMatch =
# CratesNvimUpgrade =
# CratesNvimError =
# CratesNvimPopupPillText =
# CratesNvimPopupPillBorder =
# CratesNvimPopupDescription =
# CratesNvimPopupLabel =
# CratesNvimPopupVersion =
# CratesNvimPopupPreRelease =
# CratesNvimPopupYanked =
# CratesNvimPopupVersionDate =
# CratesNvimPopupFeature =
# CratesNvimPopupEnabled =
# CratesNvimPopupTransitive =
# CratesNvimPopupDependency =
# CratesNvimPopupOptional =
# CratesNvimPopupDependencyVersion =
# CratesNvimPopupLoading =

[Misc]
diffAdded = 'sign_add'
diffRemoved = 'sign_delete'
diffFileId = 'blue - br'
diffFile = 'alt_bg'
diffNewFile = 'green'
diffOldFile = 'red'
debugPc = '- ui5'
debugBreakpoint = 'red - r'

CodiVirtualText = 'hint'
SniprunVirtualTextOk = 'hint'
SniprunFloatingWinOk = 'hint'
SniprunVirtualTextErr = 'error'
SniprunFloatingWinErr = 'error'

DapBreakpoint = 'error'

[Language]
## XML
xmlTag = 'green'
xmlTagName = 'green'

## YAML
xmlEndTag = 'green'
yamlPlainScalar = 'orange'
yamlTSField = 'blue'

## lua
luaFunc = 'yellow'
luaFunction = 'blue'

## hcl
hclTSPunctSpecial = 'alt_fg'

## html
htmlH1 = 'fg'
htmlH2 = 'fg'
htmlH3 = 'fg'
htmlH4 = 'fg'
htmlH5 = 'fg'
htmlH6 = 'fg'
htmlHead = 'fg'
htmlTitle = 'fg'
htmlArg = 'fg'
htmlTag = 'ui3'
htmlTagN = 'ui3'
htmlTagName = 'ui3'
htmlComment = 'dark_gray'
htmlLink = 'orange - u'

## css
cssBraces = 'fg'
cssInclude = 'purple'
cssTagName = 'yellow'
cssClassName = 'yellow'
cssPseudoClass = 'yellow'
cssPseudoClassId = 'yellow'
cssPseudoClassLang = 'yellow'
cssIdentifier = 'yellow'
cssProp = 'fg'
cssDefinition = 'fg'
cssAttr = 'orange'
cssAttrRegion = 'orange'
cssColor = 'orange'
cssFunction = 'purple'
cssFunctionName = 'yellow'
cssVendor = 'orange'
cssValueNumber = 'orange'
cssValueLength = 'orange'
cssUnitDecorators = 'orange'
cssStyle = 'fg'
cssImportant = 'blue'

## json
jsonKeyword = 'blue'

## yaml
yamlBlockMappingKey = 'blue'

## yaml
tomlTSProperty = 'blue'
