local Treesitter = {
  TSComment = { fg = C.gray },
  TSAnnotation = { fg = C.purple },
  TSAttribute = { fg = C.cyan },
  TSConstructor = { fg = C.tester },
  TSType = { fg = C.alt_yellow },
  TSTypeBuiltin = { fg = C.purple },
  TSConditional = { fg = C.blue },
  TSException = { fg = C.blue },
  TSInclude = { fg = C.blue },
  TSKeyword = { fg = C.blue },
  TSKeywordFunction = { fg = C.alt_green },
  TSLabel = { fg = C.blue },
  TSNamespace = { fg = C.magenta },
  TSRepeat = { fg = C.orange },
  TSConstant = { fg = C.red },
  TSConstBuiltin = { fg = C.red },
  TSFloat = { fg = C.alt_cyan },
  TSNumber = { fg = C.magenta },
  TSBoolean = { fg = C.alt_cyan },
  TSCharacter = { fg = C.light_green },
  TSError = { fg = C.error_red },
  TSFunction = { fg = C.yellow },
  TSFuncBuiltin = { fg = C.alt_yellow },
  TSMethod = { fg = C.yellow },
  TSConstMacro = { fg = C.cyan },
  TSFuncMacro = { fg = C.cyan },
  TSVariable = { fg = C.magenta },
  TSVariableBuiltin = { fg = C.cyan },
  TSProperty = { fg = C.hint_blue },
  TSOperator = { fg = C.gray_blue },
  TSField = { fg = C.white },
  TSParameter = { fg = C.white },
  TSParameterReference = { fg = C.white },
  TSSymbol = { fg = C.white },
  TSText = { fg = C.fg },
  TSPunctDelimiter = { fg = C.light_gray },
  TSTagDelimiter = { fg = C.light_gray },
  TSPunctBracket = { fg = C.light_gray },
  TSPunctSpecial = { fg = C.light_gray },
  TSString = { fg = C.alt_green },
  TSStringRegex = { fg = C.green },
  TSStringEscape = { fg = C.light_green },
  TSTag = { fg = C.blue },
  TSEmphasis = { style = "italic" },
  TSUnderline = { style = "underline" },
  TSTitle = { fg = C.blue, style = "bold" },
  TSLiteral = { fg = C.green },
  TSURI = { fg = C.cyan, style = "underline" },
  TSKeywordOperator = { fg = C.blue },
  TSKeywordReturn = { fg = C.orange },
  TSStructure = { fg = C.purple_test },
  TSStrong = { fg = C.yellow },
  TSQueryLinterError = { fg = C.warning_orange },
}

return Treesitter
